[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
